baseURL: https://download.spideroak.com
title: "SpiderOak Software Product Downloads"
defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1
MetaDataFormat: "yaml"
theme: "hugo-three"
googleAnalytics: ""
relativeURLs: true
taxonomies:
  category: categories
  tag: tags
  product: products
menu: 
  main: 
    - identifier: share
      url: /share/
      weight: 1
    - name: one
      url: /one/
      weight: 2