baseurl = "https://download.spideroak.com"
defaultContentLanguage = "en"
languageCode = "en"
theme = "hugo-three"
enableRobotsTXT = true
metaDataFormat = "yaml"
title = "SpiderOak Downloads"

# [params]
#   mainSections = ["share", "semaphor", "one", "groups", "notes"]

[blackfriday]
hrefTargetBlank = false
latexDashes = true
plainIDAnchors = true

[[menu.main]]
identifier = "share"
name = "Share Menu Item"
url = "/share/"
weight = 1
[[menu.main]]
identifier = "semaphor"
name = "Semaphor"
url = "/semaphor/"
weight = 2
[[menu.main]]
identifier = "one"
name = "One Backup"
url = "/one/"
weight = 3
[[menu.main]]
identifier = "groups"
name = "Groups Backup"
url = "/groups/"
weight = 4
[[menu.main]]
identifier = "notes"
name = "Release Notes"
url = "/notes/"
weight = 5
[[menu.main]]
identifier = "support"
name = "SpiderOak Support"
url = "https://spideroak.support/hc/en-us/"
weight = 6


# [outputFormats.Redirects]
# baseName = "redirects"
# isPlainText = true
# mediatype = "application/json"
# notAlternative = true
# [outputs]
# home = ["HTML", "RSS", "OpenSearch", "Algolia", "Redirects"]

[social]
email = "https://spideroak.support/hc/en-us/requests/new"
twitter = "spideroak"
facebook = "SpiderOak"
vimeo = "spideroak"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"
release = "releases"
product = "products"
